### ISSUE TITLE
Unclear what format the data parameters is expecting

### ISSUE THREAD

**Issue by lozandier** [codeschool/TweetValidator#1]
Based on the current contents of  `readme.md`, it's unclear how to proceed with the task of formatting data to adhere to this API.

**Comment by douglaswileythedatascientist** [comment]
Hello,
The hint says that the 'data key should take an object of request parameters', plus the app.js here is looking for a 'description' value in the body - so behold - this worked for me:

```
data: { description: potentialTweet } 
```

:) Doug

**Comment by RonanCodes** [comment]
Thanks @dougwiley that worked for me.
Still getting used to the $http stuff.

**Comment by imichelakos** [comment]
Still the documentation is in low level.

**Comment by jbasilio** [comment]
Even the `curl` example doesn't work

**Comment by ozluy** [comment]
data: { description: potentialTweet } 
worked for me thanks :)

**Comment by janmchan** [comment]
Does anybody know how to make this work using "Advanced REST Client"? https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo

**Comment by caike** [comment]
Fixed with #2
